### ISSUE TITLE
插件包的区别

### ISSUE THREAD

**Issue by shorexilin** [Leibnizhu/sonar-pmd-p3c-jdk17#163]
你好，这三个包有什么区别？
![1708669367622](https://github.com/Leibnizhu/sonar-pmd-p3c-jdk17/assets/52094488/48a72ab4-af49-4cde-8f7e-d11ad46db726)

**Comment by Leibnizhu** [comment]
分别是：

- javadoc文档
- 源码
- 编译后的可用jar
