### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by persistent268** [Leibnizhu/sonar-pmd-p3c-jdk17#97]
希望有个package，自己打包，总是报错,显示无法访问org.sonar.api.batch.rule.ActiveRules

**Comment by Leibnizhu** [comment]
@persistent268  把workflow改了下，打了个release：

- https://github.com/Leibnizhu/sonar-pmd-p3c-jdk17/releases/tag/1.0.0
- https://github.com/Leibnizhu/sonar-pmd-p3c-jdk17/releases/download/1.0.0/sonar-pmd-plugin-1.0.0.jar

**Comment by persistent268** [comment]
嗯嗯，谢啦
